services:
  postgres:
    container_name: spring-security-keycloak-db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: javawhizz
      POSTGRES_USER: javawhizz
      POSTGRES_PASSWORD: javawhizz
    shm_size: 128mb
    networks:
      - keycloak-network

  keycloak:
    container_name: spring-security-keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: info
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge




